-- Dropshipping Warashibe research persistence.
-- Append-only evidence tables. This migration does not enable live commerce.

create table if not exists dropship_observations (
    id bigint generated by default as identity primary key,
    product_key text not null,
    supplier text,
    source text,
    observed_at timestamptz not null default now(),
    observation jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists dropship_observations_product_time_idx
    on dropship_observations (product_key, observed_at desc);

create table if not exists dropship_audit_log (
    id bigint generated by default as identity primary key,
    sha256 text not null unique,
    event_type text,
    record jsonb not null,
    created_at timestamptz not null default now()
);

create table if not exists dropship_research_snapshots (
    id bigint generated by default as identity primary key,
    sha256 text not null unique,
    maturity_stage text,
    snapshot jsonb not null,
    observed_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

comment on table dropship_observations is
    'Append-only supplier/product observations for dropshipping research.';

comment on table dropship_audit_log is
    'Append-only audit evidence. No live commerce authorization.';

comment on table dropship_research_snapshots is
    'Append-only research maturity snapshots. No live commerce authorization.';
