-- PG-034: Trade Settlement / Capital Update audit.

create table if not exists public.warashibe_trade_settlements (
  id bigint generated by default as identity primary key,
  settlement_key text not null unique,
  listing_idempotency_key text not null unique,
  item_key text not null,
  marketplace text not null,
  settlement jsonb not null,
  settled_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_trade_settlements enable row level security;
revoke all on table public.warashibe_trade_settlements from anon, authenticated;

create index if not exists warashibe_trade_settlements_marketplace_idx
  on public.warashibe_trade_settlements (marketplace, settled_at desc);

-- Closed-by-default. Settlement preserves uncommitted cash and computes
-- next deployable capital for the next Warashibe candidate cycle.
