-- PG-035: One-cycle Warashibe Proof audit.

create table if not exists public.warashibe_one_cycle_proofs (
  id bigint generated by default as identity primary key,
  proof_key text not null unique,
  item_key text not null,
  proof_mode text not null,
  proof jsonb not null,
  completed_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_one_cycle_proofs enable row level security;
revoke all on table public.warashibe_one_cycle_proofs from anon, authenticated;

create index if not exists warashibe_one_cycle_proofs_mode_idx
  on public.warashibe_one_cycle_proofs (proof_mode, completed_at desc);

-- Synthetic proof must remain explicitly distinct from verified live external commerce.
-- One-cycle proof never authorizes controlled automation.
