-- PG-025: append-only Human Go/No-Go live-pilot decisions.

create table if not exists public.warashibe_live_pilot_decisions (
  id bigint generated by default as identity primary key,
  decision_key text not null unique,
  source_audit_key text not null,
  decision text not null check (decision in ('go','no_go')),
  reviewer_id text not null,
  pilot_scope jsonb not null,
  decided_at timestamptz not null,
  valid_until timestamptz not null,
  decision_payload jsonb not null,
  created_at timestamptz not null default now(),
  check (valid_until > decided_at)
);

alter table public.warashibe_live_pilot_decisions enable row level security;

create index if not exists warashibe_live_pilot_decision_audit_idx
  on public.warashibe_live_pilot_decisions (source_audit_key, decided_at desc);

-- No public/anon policies are created.
-- GO records scope only. It does not authorize live execution or commerce.
