-- PG-032: Human Sale Decision audit.

create table if not exists public.warashibe_human_sale_decisions (
  id bigint generated by default as identity primary key,
  decision_key text not null unique,
  plan_key text not null unique,
  item_key text not null,
  marketplace text not null,
  decision text not null check (decision in ('sell','do_not_sell')),
  decision_payload jsonb not null,
  decided_at timestamptz not null,
  valid_until timestamptz not null,
  created_at timestamptz not null default now(),
  check (valid_until > decided_at)
);

alter table public.warashibe_human_sale_decisions enable row level security;
revoke all on table public.warashibe_human_sale_decisions from anon, authenticated;

-- Closed-by-default. SELL authorizes one bounded listing attempt only.
-- The decision record itself does not create a listing or complete a sale.
