-- PG-021: append-only Human Pilot Sessions.
-- Non-destructive: creates one isolated Warashibe-owned table and indexes.

create table if not exists public.warashibe_pilot_sessions (
  id bigint generated by default as identity primary key,
  session_key text not null unique,
  record_key text not null,
  plan_key text not null,
  identity_key text not null,
  session_state text not null check (session_state = 'awaiting_human_final_confirmation'),
  session jsonb not null,
  started_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_pilot_sessions enable row level security;

create index if not exists warashibe_pilot_identity_started_idx
  on public.warashibe_pilot_sessions (identity_key, started_at desc);

create index if not exists warashibe_pilot_plan_idx
  on public.warashibe_pilot_sessions (plan_key);

-- No public/anon policies are created.
-- Pilot sessions remain dry-run and await explicit human final confirmation.
