-- PG-030: Receive / Inspection audit.

create table if not exists public.warashibe_receive_inspections (
  id bigint generated by default as identity primary key,
  inspection_key text not null unique,
  receipt_key text not null unique,
  provider text not null,
  item_key text not null,
  disposition text not null check (disposition in ('sale_ready','return_required','inspection_hold')),
  inspection jsonb not null,
  inspected_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_receive_inspections enable row level security;
revoke all on table public.warashibe_receive_inspections from anon, authenticated;

create index if not exists warashibe_receive_inspections_disposition_idx
  on public.warashibe_receive_inspections (disposition, inspected_at desc);

-- Closed-by-default. sale_ready may proceed to PG-031 Sale Plan.
-- return_required and inspection_hold must not proceed to sale automatically.
