-- Runtime deployment status cache for Warashibe AI.
-- Render/GitHub remain sources of truth; this table is append-only audit evidence.

create table if not exists public.warashibe_runtime_status (
  id bigint generated by default as identity primary key,
  snapshot_key text not null unique,
  service_name text not null,
  service_id text not null,
  branch text not null,
  git_head_sha text not null,
  ci_sha text not null,
  ci_status text not null,
  render_live_sha text not null,
  render_deploy_id text not null,
  render_status text not null,
  deployment_consistent boolean not null,
  source text not null,
  snapshot jsonb not null,
  observed_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_runtime_status enable row level security;
revoke all on table public.warashibe_runtime_status from anon, authenticated;

create index if not exists warashibe_runtime_status_latest_idx
  on public.warashibe_runtime_status (service_name, branch, observed_at desc);

create index if not exists warashibe_runtime_status_sha_idx
  on public.warashibe_runtime_status (git_head_sha, ci_sha, render_live_sha);

-- This table never authorizes deployment, commerce, payments, or automation.
