-- PG-018: append-only economic assessments for dry-run commerce plans.
-- Non-destructive: creates one isolated Warashibe-owned table and indexes.

create table if not exists public.warashibe_economic_assessments (
  id bigint generated by default as identity primary key,
  assessment_key text not null unique,
  plan_key text not null,
  identity_key text not null,
  economics jsonb not null,
  evaluated_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_economic_assessments enable row level security;

create index if not exists warashibe_economic_identity_evaluated_idx
  on public.warashibe_economic_assessments (identity_key, evaluated_at desc);

create index if not exists warashibe_economic_plan_idx
  on public.warashibe_economic_assessments (plan_key);

-- No public/anon policies are created.
-- Economic viability is analysis only and never authorizes commerce.
