-- PG-027: append-only live-adapter validation artifacts.

create table if not exists public.warashibe_live_adapter_validations (
  id bigint generated by default as identity primary key,
  validation_key text not null unique,
  provider text not null,
  item_key text not null,
  validation jsonb not null,
  validated_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_live_adapter_validations enable row level security;

create index if not exists warashibe_live_adapter_provider_validated_idx
  on public.warashibe_live_adapter_validations (provider, validated_at desc);

-- No public/anon policies are created.
-- Validation may mark an order as eligible for Human Final Buy review only.
-- submit/status/cancel stay blocked before PG-028 and no external network write occurs.
