-- PG-033: Limited Sale Execution audit.

create table if not exists public.warashibe_limited_sale_executions (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  decision_key text not null unique,
  plan_key text not null,
  item_key text not null,
  marketplace text not null,
  result jsonb not null,
  executed_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_limited_sale_executions enable row level security;
revoke all on table public.warashibe_limited_sale_executions from anon, authenticated;

create index if not exists warashibe_limited_sale_marketplace_idx
  on public.warashibe_limited_sale_executions (marketplace, executed_at desc);

-- Closed-by-default.
-- One idempotency key and one human sale decision may produce at most one listing audit row.
-- Sale completion and settlement are separate later stages.
