-- PG-031: Sale Plan audit.

create table if not exists public.warashibe_sale_plans (
  id bigint generated by default as identity primary key,
  plan_key text not null unique,
  inspection_key text not null unique,
  item_key text not null,
  marketplace text not null,
  plan jsonb not null,
  planned_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_sale_plans enable row level security;
revoke all on table public.warashibe_sale_plans from anon, authenticated;

create index if not exists warashibe_sale_plans_marketplace_idx
  on public.warashibe_sale_plans (marketplace, planned_at desc);

-- Closed-by-default. A sale plan records economics and Capital Velocity only.
-- It never authorizes listing or sale execution.
