-- PG-028: Human Final Buy confirmations and single-purchase execution audit.
-- Live execution remains externally disabled unless an explicit runtime integration is separately configured.

create table if not exists public.warashibe_human_final_buy_confirmations (
  id bigint generated by default as identity primary key,
  confirmation_key text not null unique,
  provider text not null,
  item_key text not null,
  decision text not null check (decision in ('buy','do_not_buy')),
  confirmation jsonb not null,
  confirmed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (expires_at > confirmed_at)
);

alter table public.warashibe_human_final_buy_confirmations enable row level security;
revoke all on table public.warashibe_human_final_buy_confirmations from anon, authenticated;

create table if not exists public.warashibe_single_purchase_executions (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  confirmation_key text not null unique,
  provider text not null,
  item_key text not null,
  result jsonb not null,
  executed_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint warashibe_single_purchase_confirmation_fk
    foreign key (confirmation_key)
    references public.warashibe_human_final_buy_confirmations(confirmation_key)
);

alter table public.warashibe_single_purchase_executions enable row level security;
revoke all on table public.warashibe_single_purchase_executions from anon, authenticated;

create index if not exists warashibe_final_buy_provider_confirmed_idx
  on public.warashibe_human_final_buy_confirmations (provider, confirmed_at desc);

create index if not exists warashibe_single_purchase_provider_executed_idx
  on public.warashibe_single_purchase_executions (provider, executed_at desc);

-- No anon/authenticated grants or policies are created.
-- The execution table enforces one row per idempotency key and one row per final-buy confirmation.
