-- PG-017: append-only dry-run commerce plans.
-- Non-destructive: creates one isolated Warashibe-owned table and indexes.

create table if not exists public.warashibe_dry_run_plans (
  id bigint generated by default as identity primary key,
  plan_key text not null unique,
  source_record_key text not null,
  identity_key text not null,
  review_decision text not null check (review_decision = 'approve'),
  plan jsonb not null,
  generated_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_dry_run_plans enable row level security;

create index if not exists warashibe_dry_run_identity_generated_idx
  on public.warashibe_dry_run_plans (identity_key, generated_at desc);

create index if not exists warashibe_dry_run_source_record_idx
  on public.warashibe_dry_run_plans (source_record_key);

-- No public/anon policies are created.
-- Plans are server-side audit artifacts only; they never authorize commerce.
