-- PG-029: Purchase Receipt / Reconciliation audit.

create table if not exists public.warashibe_purchase_receipts (
  id bigint generated by default as identity primary key,
  receipt_key text not null unique,
  idempotency_key text not null unique,
  provider text not null,
  item_key text not null,
  provider_order_reference text not null,
  receipt jsonb not null,
  reconciled_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_purchase_receipts enable row level security;
revoke all on table public.warashibe_purchase_receipts from anon, authenticated;

create index if not exists warashibe_purchase_receipts_provider_idx
  on public.warashibe_purchase_receipts (provider, reconciled_at desc);

-- Closed-by-default. A reconciled receipt fixes actual capital committed
-- before the receive/inspection stage.
