-- PG-020: append-only pre-flight safety assessments.
-- Non-destructive: creates one isolated Warashibe-owned table and indexes.

create table if not exists public.warashibe_preflight_assessments (
  id bigint generated by default as identity primary key,
  preflight_key text not null unique,
  record_key text not null,
  plan_key text not null,
  identity_key text not null,
  preflight jsonb not null,
  evaluated_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_preflight_assessments enable row level security;

create index if not exists warashibe_preflight_identity_evaluated_idx
  on public.warashibe_preflight_assessments (identity_key, evaluated_at desc);

create index if not exists warashibe_preflight_plan_idx
  on public.warashibe_preflight_assessments (plan_key);

-- No public/anon policies are created.
-- Passing pre-flight means only ready_for_human_purchase_confirmation.
-- It never authorizes or executes purchase, payment, listing, or sale.
