-- PG-023: append-only sandbox commerce attempt audit.
-- Non-destructive: creates one isolated Warashibe-owned table and index.

create table if not exists public.warashibe_sandbox_commerce_attempts (
  id bigint generated by default as identity primary key,
  attempt_key text not null unique,
  intent_key text not null,
  provider text not null,
  requested_action text not null,
  result jsonb not null,
  attempted_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_sandbox_commerce_attempts enable row level security;

create index if not exists warashibe_sandbox_attempt_intent_idx
  on public.warashibe_sandbox_commerce_attempts (intent_key, attempted_at desc);

-- No public/anon policies are created.
-- Every adapter action is sandbox_noop and must not perform any network/external write.
