-- PG-036: Live Pilot Review audit.

create table if not exists public.warashibe_live_pilot_reviews (
  id bigint generated by default as identity primary key,
  review_key text not null unique,
  proof_key text not null unique,
  item_key text not null,
  review_mode text not null,
  review jsonb not null,
  reviewed_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_live_pilot_reviews enable row level security;
revoke all on table public.warashibe_live_pilot_reviews from anon, authenticated;

create index if not exists warashibe_live_pilot_reviews_mode_idx
  on public.warashibe_live_pilot_reviews (review_mode, reviewed_at desc);

-- Review produces Learning Loop feedback only.
-- It never authorizes controlled automation automatically.
