-- PG-015: append-only cross-market comparison/proposal history.
-- Applied to the Warashibe Supabase project on 2026-10-02.
-- Non-destructive: creates one isolated Warashibe-owned table and index.

create table if not exists public.warashibe_cross_market_records (
  id bigint generated by default as identity primary key,
  record_key text not null unique,
  identity_key text not null,
  comparison jsonb not null check (jsonb_typeof(comparison) = 'object'),
  proposal jsonb not null check (jsonb_typeof(proposal) = 'object'),
  observed_at timestamptz not null,
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint warashibe_cross_market_time_order check (captured_at >= observed_at)
);

alter table public.warashibe_cross_market_records enable row level security;

create index if not exists warashibe_cross_market_identity_captured_idx
  on public.warashibe_cross_market_records (identity_key, captured_at desc);

-- No anon/public policies are created.
-- The product path is server-side only and must fail closed for public clients.
