-- PG-022: append-only Purchase Intent Records.
-- Non-destructive: creates one isolated Warashibe-owned table and indexes.

create table if not exists public.warashibe_purchase_intents (
  id bigint generated by default as identity primary key,
  intent_key text not null unique,
  session_key text not null unique,
  record_key text not null,
  plan_key text not null,
  identity_key text not null,
  intent jsonb not null,
  confirmed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (expires_at > confirmed_at)
);

alter table public.warashibe_purchase_intents enable row level security;

create index if not exists warashibe_purchase_intent_identity_confirmed_idx
  on public.warashibe_purchase_intents (identity_key, confirmed_at desc);

create index if not exists warashibe_purchase_intent_plan_idx
  on public.warashibe_purchase_intents (plan_key);

-- No public/anon policies are created.
-- Intent is a human confirmation record only. It never authorizes order submission.
