-- PG-024: append-only Live-readiness Audits.
-- Non-destructive: creates one isolated Warashibe-owned table and index.

create table if not exists public.warashibe_live_readiness_audits (
  id bigint generated by default as identity primary key,
  audit_key text not null unique,
  auditor_id text not null,
  audited_at timestamptz not null,
  audit jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_live_readiness_audits enable row level security;

create index if not exists warashibe_live_readiness_audited_idx
  on public.warashibe_live_readiness_audits (audited_at desc);

-- No public/anon policies are created.
-- Passing the audit only enables a human go/no-go review.
-- It never authorizes live purchase, payment, listing, or sale.
