-- PG-016: append-only Human Review audit decisions.
-- Non-destructive: creates one isolated Warashibe-owned table and index.

create table if not exists public.warashibe_review_decisions (
  id bigint generated by default as identity primary key,
  record_key text not null unique,
  identity_key text not null,
  decision text not null check (decision in ('approve','reject')),
  reviewer_id text not null,
  reason text not null,
  reviewed_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.warashibe_review_decisions enable row level security;

create index if not exists warashibe_review_identity_reviewed_idx
  on public.warashibe_review_decisions (identity_key, reviewed_at desc);

-- No public/anon policies are created.
-- Review writes are server-side only and require the application review-code gate.
