"""Render future Supabase migration SQL without executing it.

This module is offline only. It creates SQL text for human review and performs
no network calls, authentication, or database mutation.
"""

from research_lab.supabase_schema_contract import TABLES
from research_lab.supabase_schema_migration_plan import PROTECTED_EXISTING_TABLES

SQL_RENDERER_VERSION = "0.1"


def render_create_table_sql(table):
    if table not in TABLES:
        raise ValueError("unknown Warashibe table")
    if table in PROTECTED_EXISTING_TABLES:
        raise ValueError("protected existing table")

    if table == "warashibe_sale_outcomes":
        return """create table public.warashibe_sale_outcomes (
    id bigint generated by default as identity primary key,
    opportunity_key text not null,
    sold boolean not null,
    days_to_outcome integer,
    created_at timestamptz not null default now()
);"""

    if table == "warashibe_market_evidence":
        return """create table public.warashibe_market_evidence (
    id bigint generated by default as identity primary key,
    source text not null,
    external_id text not null,
    identity_key text,
    purchase_price numeric not null check (purchase_price >= 0),
    expected_sale_price numeric not null check (expected_sale_price >= 0),
    observed_at timestamptz not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);"""

    raise ValueError("unsupported Warashibe table")


def render_security_sql(table):
    if table not in TABLES:
        raise ValueError("unknown Warashibe table")
    return f"""alter table public.{table} enable row level security;
revoke all on table public.{table} from anon;"""


def render_full_migration_sql():
    statements = []
    for table in TABLES:
        statements.append(render_create_table_sql(table))
        statements.append(render_security_sql(table))
    sql = "\n\n".join(statements)
    assert "public.videos" not in sql
    return sql
